stages:
  - verify
  - build

variables:
  GO_VERSION: "1.25"
  GOLANGCI_LINT_VERSION: "v2.11"

### VERIFY ####################################################################
compile:
  stage: verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  image: golang:$GO_VERSION
  cache:
    key: go-mod-$CI_COMMIT_REF_SLUG
    paths:
      - .go-mod-cache/
  variables:
    GOMODCACHE: "$CI_PROJECT_DIR/.go-mod-cache"
  script:
    - go build ./...

lint:
  stage: verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION-alpine
  cache:
    key: golangci-$CI_COMMIT_REF_SLUG
    paths:
      - .golangci-cache/
  variables:
    GOLANGCI_LINT_CACHE: "$CI_PROJECT_DIR/.golangci-cache"
  script:
    - go mod download
    - golangci-lint run

test:
  stage: verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  image: golang:$GO_VERSION
  cache:
    key: go-mod-$CI_COMMIT_REF_SLUG
    paths:
      - .go-mod-cache/
  variables:
    GOMODCACHE: "$CI_PROJECT_DIR/.go-mod-cache"
  script:
    - go test ./...

alerts:
  stage: verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  image:
    name: prom/prometheus:v2.53.0
    entrypoint: [""]
  script:
    - promtool check rules examples/monitoring/alerts.yaml


### BUILD IMAGE ###############################################################
build-image:
  stage: build
  image:
    name: registry.gitlab.com/flarenetwork/infra-public/pipeliner/kaniko-executor-stbl:v1.23.2-debug
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  variables:
    DOCKERFILE: "Dockerfile"
    IMAGE: "tee-proxy"
  script:
    - >-
      args="--context ${CI_PROJECT_DIR}
        --dockerfile ${CI_PROJECT_DIR}/${DOCKERFILE}
        --build-arg REVISION=${CI_COMMIT_SHA}
        --registry-mirror mirror.gcr.io
        --compressed-caching=false
        --snapshot-mode=redo
        --no-push"
    - /kaniko/executor $args
